name: Pull requests

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'
      - '*.toml'
      - '*.yml'
      - '*.yaml'
      - '*.ini'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  tests:
    uses: ./.github/workflows/_tests.yaml

  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # 4.1.1
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@5ce82f5d814d4010519d15f0552aec4f17a1e1fe # 5.4.5
